name: Build artifacts for Linux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Faust compiler with Docker
        run: |
          git clone https://github.com/grame-cncm/faust.git
          cd faust
          git submodule update --init
          docker build . --tag faust

